name: mosaic
channels:
  - plotly 
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - click>=8.1.2
  - h5py>=2.10.0
  - hdbscan>=0.8.28
  - matplotlib>=3.2.2
  - numpy>=1.20.3
  - pandas>=1.0.5
  - plotly>=5.8.0
  - python-igraph>=0.8.3
  - requests>=2.22.0
  - scikit-allel>=1.2.1
  - scikit-learn>=1.0.2
  - scipy>=1.7.3
  - seaborn>=0.10.1
  - umap-learn>=0.4.6
  - ipykernel
  # --- plotly ---
  - ipywidgets>=7.0.0
  - nbformat>=4.2.0
  - python-kaleido # <---- seems to cause some issue on some linux distribution